name: Js Action

on: push

jobs:
  simple-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: CheckOut
        uses: actions/checkout@v1   
      - name: List Files
        run: |
          pwd 
          ls 
      - name: echo my name
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Uvesh
      - name: time output
        run: echo "${{steps.greet.outputs.time}}"


        
