name: matrix
on:
  push:
    
jobs:
  node-update:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node -v
      - name: change node version
        uses: actions/setup-node@v2
        with:
          node-version: 6
      - name: log new node version
        run: node -v    
        